# Site settings
title: Vinařství Pelánek
description: Rodinné vinařství s vinným sklepem ve Velké Bíteši. vína jsou původem z České republiky, z vinařské oblasti Morava, podoblasti Mikulovské, z vinařské obce Novosedly.
owner: Josef Pelánek # or company name
first_published: 2018 # if migrating another site, the year of your first publish
lang: cs_cz
email: info@vinarstvipelanek.cz
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vinarstvipelanek.cz" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/pg/Vinařství-Pelánek-1510129645951146
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: info@vinarstvipelanek.cz
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

collections:
  - wines

# Build settings
markdown: kramdown
#sass:
#  style: compressed

google_analytics: "UA-129402124-1"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - elements.html
  - generic.html